### ISSUE TITLE
clearly indicate when a search has no matches

### ISSUE THREAD

**Issue by wydengyre** [Aerion/rss-radio-france-pour-tous#5]
To reproduce: open https://radio-france-rss.aerion.workers.dev and search for "blrf"

To the user, it will look like nothing is happening. There should be some indication that a search was attempted, and it yielded no results.

**Comment by Aerion** [comment]
Thanks for raising this issue, here is how it now looks like
![image](https://github.com/Aerion/rss-radio-france-pour-tous/assets/9089317/44836d7e-3cfd-4d59-9850-41b156d2fc68)
